//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:45:13 AM GMT 
//


package com.jroc.trainingprocessor.model.trainingcenterdatabase;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildType_t.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BuildType_t"&gt;
 *   &lt;restriction base="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}Token_t"&gt;
 *     &lt;enumeration value="Internal"/&gt;
 *     &lt;enumeration value="Alpha"/&gt;
 *     &lt;enumeration value="Beta"/&gt;
 *     &lt;enumeration value="Release"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "BuildType_t")
@XmlEnum
public enum BuildTypeT {

  @XmlEnumValue("Internal")
  INTERNAL("Internal"),
  @XmlEnumValue("Alpha")
  ALPHA("Alpha"),
  @XmlEnumValue("Beta")
  BETA("Beta"),
  @XmlEnumValue("Release")
  RELEASE("Release");
  private final String value;

  BuildTypeT(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static BuildTypeT fromValue(String v) {
    for (BuildTypeT c : BuildTypeT.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

}
