//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:45:13 AM GMT 
//


package com.jroc.trainingprocessor.model.trainingcenterdatabase;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MultiSportSession_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MultiSportSession_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="FirstSport" type="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}FirstSport_t"/&gt;
 *         &lt;element name="NextSport" type="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}NextSport_t" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiSportSession_t", propOrder = {
    "id",
    "firstSport",
    "nextSport",
    "notes"
})
public class MultiSportSessionT {

  @XmlElement(name = "Id", required = true)
  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar id;
  @XmlElement(name = "FirstSport", required = true)
  protected FirstSportT firstSport;
  @XmlElement(name = "NextSport")
  protected List<NextSportT> nextSport;
  @XmlElement(name = "Notes")
  protected String notes;

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setId(XMLGregorianCalendar value) {
    this.id = value;
  }

  /**
   * Gets the value of the firstSport property.
   *
   * @return possible object is {@link FirstSportT }
   */
  public FirstSportT getFirstSport() {
    return firstSport;
  }

  /**
   * Sets the value of the firstSport property.
   *
   * @param value allowed object is {@link FirstSportT }
   */
  public void setFirstSport(FirstSportT value) {
    this.firstSport = value;
  }

  /**
   * Gets the value of the nextSport property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the nextSport property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getNextSport().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link NextSportT }
   */
  public List<NextSportT> getNextSport() {
    if (nextSport == null) {
      nextSport = new ArrayList<NextSportT>();
    }
    return this.nextSport;
  }

  /**
   * Gets the value of the notes property.
   *
   * @return possible object is {@link String }
   */
  public String getNotes() {
    return notes;
  }

  /**
   * Sets the value of the notes property.
   *
   * @param value allowed object is {@link String }
   */
  public void setNotes(String value) {
    this.notes = value;
  }

}
