//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:45:13 AM GMT 
//


package com.jroc.trainingprocessor.model.trainingcenterdatabase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Position_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Position_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LatitudeDegrees" type="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}DegreesLatitude_t"/&gt;
 *         &lt;element name="LongitudeDegrees" type="{http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2}DegreesLongitude_t"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Position_t", propOrder = {
    "latitudeDegrees",
    "longitudeDegrees"
})
public class PositionT {

  @XmlElement(name = "LatitudeDegrees")
  protected double latitudeDegrees;
  @XmlElement(name = "LongitudeDegrees")
  protected double longitudeDegrees;

  /**
   * Gets the value of the latitudeDegrees property.
   */
  public double getLatitudeDegrees() {
    return latitudeDegrees;
  }

  /**
   * Sets the value of the latitudeDegrees property.
   */
  public void setLatitudeDegrees(double value) {
    this.latitudeDegrees = value;
  }

  /**
   * Gets the value of the longitudeDegrees property.
   */
  public double getLongitudeDegrees() {
    return longitudeDegrees;
  }

  /**
   * Sets the value of the longitudeDegrees property.
   */
  public void setLongitudeDegrees(double value) {
    this.longitudeDegrees = value;
  }

}
