//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:45:13 AM GMT 
//


package com.jroc.trainingprocessor.model.trainingcenterdatabase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuickWorkout_t complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="QuickWorkout_t"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TotalTimeSeconds" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="DistanceMeters" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuickWorkout_t", propOrder = {
    "totalTimeSeconds",
    "distanceMeters"
})
public class QuickWorkoutT {

  @XmlElement(name = "TotalTimeSeconds")
  protected double totalTimeSeconds;
  @XmlElement(name = "DistanceMeters")
  protected double distanceMeters;

  /**
   * Gets the value of the totalTimeSeconds property.
   */
  public double getTotalTimeSeconds() {
    return totalTimeSeconds;
  }

  /**
   * Sets the value of the totalTimeSeconds property.
   */
  public void setTotalTimeSeconds(double value) {
    this.totalTimeSeconds = value;
  }

  /**
   * Gets the value of the distanceMeters property.
   */
  public double getDistanceMeters() {
    return distanceMeters;
  }

  /**
   * Sets the value of the distanceMeters property.
   */
  public void setDistanceMeters(double value) {
    this.distanceMeters = value;
  }

}
